/** Synthetic source metadata and transcript for browser and controller evidence. */
import { brandString } from '@deepseek-ai/dsh-brand'
import type { CodingSessionMirror } from '@deepseek-ai/dsh-coding-session/types'
import type { CodingSessionsApi } from '../src/client/controller.ts'
/** One explicitly read-only original native coding session. */
export const mirror: CodingSessionMirror = { id: brandString<CodingSessionMirror['id']>('mirror-a'), source: { provider: 'codex', profileId: brandString<CodingSessionMirror['source']['profileId']>('authorized-local-profile'), nativeSessionId: brandString<CodingSessionMirror['source']['nativeSessionId']>('native-original') }, title: 'Parser repair', cwd: '/fixture/project', writerState: 'idle', events: [{ id: brandString<CodingSessionMirror['events'][number]['id']>('native-event-1'), role: 'user', text: 'Inspect parser', digest: 'digest' }], cursor: 'cursor', digest: 'digest', revision: 1, refreshedAt: '2026-10-09T00:00:00Z', status: 'ready', capabilities: { discover: true, read: true, refresh: true, continue: false, reason: 'native-writer-handoff-unavailable' } }
/** @param value - synthetic result value. @returns generated-Remote success envelope. */
export const ok = <T>(value: T) => Promise.resolve({ ok: true as const, value })
/** @returns external-native fixture methods; production controller owns all state changes. */
export function fixtureApi(): CodingSessionsApi { const { events, ...summary } = mirror; return { getState: () => ok({ sources: [{ provider: 'codex', profileId: mirror.source.profileId, label: 'Local Codex', connected: true, capabilities: mirror.capabilities }], mirrors: [{ ...summary, eventCount: events.length }] }), discover: () => ok({ items: [{ source: mirror.source, title: mirror.title, writerState: 'idle' }], nextCursor: 'page-two' }), importSession: () => ok(mirror), refreshMirror: () => ok({ ...mirror, revision: 2, events: [...mirror.events, { id: brandString<CodingSessionMirror['events'][number]['id']>('native-event-2'), role: 'assistant', text: 'Parser repaired in the native session', digest: 'digest-2' }] }), detail: () => ok(mirror), continueSession: () => ok(mirror), claimSequential: () => ok(mirror), continueSequential: () => ok(mirror), releaseSequential: () => ok(mirror), cancelPending: () => ok(undefined) } }
